# ~/.config/hypr/hyprpaper.conf

# Preload wallpaper(s) - loads them into RAM
preload = /home/bfn/Bilder/wallpapers/monster.png
splash = false

wallpaper {
    monitor = 
    path = /home/bfn/Bilder/wallpapers/monster.png
    fit_mode = cover
}
