# ~/.config/hypr/hyprpaper.conf

# Preload wallpaper(s) - loads them into RAM
preload = /home/bfn/dotfiles/wallpapers/background.jpg
splash = false

wallpaper {
    monitor =
    path = /home/bfn/dotfiles/wallpapers/background.jpg
    fit_mode = cover
}
