################
### MONITORS ###
################

# See https://wikk.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,1.0


#monitor=DP-3,preferred,1920x0,1.0

#monitor=DP-5,preferred,3600x0,1.0
